<?php return array (
  'Consultoria' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'Consultoria Jurídica',
    'descricao' => 'Software de Consultoria Juridica',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => NULL,
  ),
  'Escalas' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://escalas.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Escalas',
    'descricao' => 'Software de Agenda Telefônica Eletrônica',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'P1' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://p1.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'P1',
    'descricao' => 'Software de Gerenciamento de Efetivo',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Sia-Auth' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://sia-auth.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Sia-Auth',
    'descricao' => 'Base de autenticação e autorização',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Notificacoes' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://notificacoes.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Notificações',
    'descricao' => 'Notificações PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Siscopom' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://siscopom.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'SISCOPOM - REVISAR',
    'descricao' => 'Sistema de Controle e Gerenciamento do COPOM/PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Agenda' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://agenda.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Agenda',
    'descricao' => 'Software de Agenda Telefônica Eletrônica',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Engenharia' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://p4.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Engenharia',
    'descricao' => 'Engenharia PMPR',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Template' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://template.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Template',
    'descricao' => 'Template PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Sargenteacao' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://sargenteacao.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Sargenteação',
    'descricao' => 'Sargenteação PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Opverao' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703793095.png',
    'color' => '#95d952',
    'appUrl' => 'https://operacaoverao.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'OPERAÇÃO VERÃO',
    'descricao' => 'Sistema da Operação Verão.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.47.0.16',
    'porta' => 443,
  ),
  'Dados' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714743726.png',
    'color' => '#0d044c',
    'appUrl' => 'https://dados.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Dados',
    'descricao' => 'Migração de Dados',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Intranet' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714762015.png',
    'color' => '#cecece',
    'appUrl' => 'https://sia.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'SIA - Acessos',
    'descricao' => 'Sistema da Intranet PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Efetivo' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703793647.png',
    'color' => '#181615',
    'appUrl' => 'https://efetivo.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'CONSULTA EFETIVO',
    'descricao' => 'Sistema de Consulta Efetivo da PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Notas' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://notas.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Notas',
    'descricao' => 'Notas para Intranet PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'QO' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703792997.png',
    'color' => '#c37038',
    'appUrl' => 'https://qo.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Quadro Organizacional',
    'descricao' => 'Software de gerenciamento do Quadro Organizacional',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Meta4' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'META4 - REVISAR',
    'descricao' => 'Sistema RH-Paraná/META4 SEAP.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => NULL,
  ),
  'Arranchamento' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703787847.png',
    'color' => '#ff5f5f',
    'appUrl' => 'https://arranchamento.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'ARRANCHAMENTO',
    'descricao' => 'Sistema de Arranchamento da PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Auditoria' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703793201.png',
    'color' => '#ae66f2',
    'appUrl' => 'https://auditoria.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'AUDITORIA',
    'descricao' => 'Sistema Auditoria de Consulta de Logs do SIA.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.25.100',
    'porta' => 443,
  ),
  'SESP - BOU' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'BOU - REVISAR',
    'descricao' => 'Funcionalidades do BOU',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => NULL,
  ),
  'SESP - LPR' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'LPR - REVISAR',
    'descricao' => 'Funcionalidades do LPR',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => NULL,
  ),
  'SESP - EPROC' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'EPROC - REVISAR',
    'descricao' => 'Funcionalidades do EPROC',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => NULL,
  ),
  'SiscopWeb' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1716992363.png',
    'color' => '#000000',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'SISCOP',
    'descricao' => 'Sistema de controle e despacho de ocorrências LEGADO',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.22.9.213',
    'porta' => NULL,
  ),
  'SIGAP' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703792710.png',
    'color' => '#d2b48c',
    'appUrl' => 'https://sigap.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'SIGAP',
    'descricao' => 'Sistema de Gerenciamento de Armas de Fogo.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Cerimonial' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703611767.png',
    'color' => 'Tan',
    'appUrl' => 'https://cerimonial.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Cerimonial',
    'descricao' => 'Software de Gerenciamento de Cerimoniais PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Sia-Ui' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714744665.png',
    'color' => '#d28ccf',
    'appUrl' => 'https://sia-ui.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Sia-Ui',
    'descricao' => 'Sistema Gerenciador do SIA - AUTH PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Cortex MJ' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714744393.png',
    'color' => '#2a214a',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'CORTEX MJ',
    'descricao' => 'Sistema de Consultas disponibilizado pelo Ministério da Justiça.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => NULL,
  ),
  'Permutas' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703792798.png',
    'color' => '#f2d45c',
    'appUrl' => 'https://permutas.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'PERMUTAS',
    'descricao' => 'Sistema de Permutas da PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Sade' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714743575.png',
    'color' => '#122888',
    'appUrl' => 'https://harpya.pm.pr.gov.br/syspm-web/public/',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'SADE',
    'descricao' => 'Sistema Principal de Atendimento e Despacho de Ocorrências.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.255',
    'porta' => NULL,
  ),
  'SAUDE' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/123456.png',
    'color' => '#17276a',
    'appUrl' => 'https://saude.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'Saúde PMPR',
    'descricao' => 'SIstema de gerenciamento de saúde',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '127.0.0.1',
    'porta' => NULL,
  ),
  'VPN' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1716993860.png',
    'color' => '#070e2a',
    'appUrl' => 'https://acessoremoto.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'VPN PMPR',
    'descricao' => 'Controla acessos da vpn para usuários PMPR',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '127.0.0.1',
    'porta' => NULL,
  ),
  'WIFIQCG' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/123456.png',
    'color' => 'Tan',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'WIFI QCG',
    'descricao' => 'Sistemas de controle de acesso a rede WIFI QCG',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '127.0.0.1',
    'porta' => NULL,
  ),
  'Monitoramento' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714744524.png',
    'color' => '#040207',
    'appUrl' => 'https://monitoramento.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'Vídeo Monitoramento',
    'descricao' => 'Software de videomonitoramento',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '127.0.0.1',
    'porta' => 443,
  ),
  'SIGEP' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714677780.png',
    'color' => '#c1c1c1',
    'appUrl' => 'https://sigep.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'SIGEP',
    'descricao' => 'Sistema de Gerenciamento de Ensino Policial da PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'TAF' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714743339.png',
    'color' => '#5fee29',
    'appUrl' => 'https://taf.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'TAF',
    'descricao' => 'Sistema de Aplicação e Controle de Teste de Aptidão Física (TAF)',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Numerador' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1714744099.png',
    'color' => '#05196e',
    'appUrl' => 'https://numerador.pm.pr.gov.br',
    'authRoute' => '/auth',
    'updateView' => '/api/update',
    'titulo' => 'NUMERADOR',
    'descricao' => 'Sistema de Numeração de Documentos da PMPR.',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => 443,
  ),
  'Consoles de Despacho' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1708713595.png',
    'color' => 'Tan',
    'appUrl' => 'https://intranet.pm.pr.gov.br',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'Consoles de Despacho',
    'descricao' => 'Consoles de Despacho',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '127.0.0.1',
    'porta' => NULL,
  ),
  'EAD-PMPR' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/123456.png',
    'color' => 'Tan',
    'appUrl' => 'https://www.ead.pm.pr.gov.br/login/index.php',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'PORTAL EAD PMPR',
    'descricao' => 'PORTAL EAD PMPR',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '127.0.0.1',
    'porta' => NULL,
  ),
  'Sesp Intranet' => 
  array (
    'img' => 'https://sia-auth.pm.pr.gov.br/images/1703787916.png',
    'color' => '#1e89e3',
    'appUrl' => 'https://www.intranet.sesp.parana/sespintranet/moduloValidacao.do?action=index',
    'authRoute' => NULL,
    'updateView' => '/api/update',
    'titulo' => 'SESP INTRANET - REVISAR',
    'descricao' => 'Sistema de Consulta da Secretaria de Segurança Pública do Paraná (SESP).',
    'class' => 'far fa-user-users fa-3x',
    'ip' => '10.147.29.225',
    'porta' => NULL,
  ),
);